---
title: "Modèles de durées"
author: "MOUSSA Aiad"
date: "9 mai 2018"
output: html_document
---

```{r}
setwd("C:/Users/ayadm/OneDrive/isup/modèle de durée")
library(survival)
mydata=read.table("modeles_durees.csv")
mydata
#print(data)
```


```{r}
survdiff(Surv(origines, delta)~M, data=mydata)
```
```{r}
cor(mydata)
```

Modèle ajusté
```{r}
cox=coxph(Surv(origines, delta) ~ Y + M + C + X1 + X2 + X3 + X4,data=mydata)
#Résumé du modèle de cox
summary(cox)
```
```{r}
res.c=cox.zph(cox)
res.c
par(mfrow=c(2,4))
plot(res.c)
```
Edition des résidus de martingales
```{r}
res.m=residuals(cox, type="martingale")
par(mfrow=c(2,2))
#Graphique résidus de martingale versus covariables non dichotomiques
#par(mfrow=c(2,1)
X = as.matrix(mydata[,c("C","M")])
for (j in 1:2) {
plot(X[,j], res.m, xlab=c("C", "M")[j], ylab="residuals")
abline(h=0, lty=2)
lines(lowess(X[,j], res.m, iter=0))}

b=coef(cox)[c(2,3)]
for (j in 1:2) {
plot(X[,j], b[j]*X[,j]+res.m, xlab=c("C","M")[j],
ylab="component+residual")
abline(lm(b[j]*X[,j]+res.m~X[,j]), lty=2)
lines(lowess(X[,j], b[j]*X[,j]+res.m, iter=0))}
```
Influence des observations
```{r}
dfbeta = residuals(cox, type="dfbeta")
par(mfrow=c(2,2))
for (j in 1:3) {
plot(dfbeta[,j], ylab=names(coef(cox))[j])
abline(h=0, lty=2)}
```

Modèle ajusté
```{r}
cox=coxph(Surv(origines, delta) ~ M + Y + X1 + X2 + X3 + X4,data=mydata)
#Résumé du modèle de cox
summary(cox)
```
il existe une influence significative d'au moins une covariable sur le taux de montant du sinistre.

```{r}
surv.mydata = with(mydata,Surv(origines, delta))
surv.mydata1 = survfit(surv.mydata ~ 1)
#plot(survfit(cox,type="fleming-harrington"), ylim=c(.7,1),
#xlab="Semaine", ylab="Proportion de non récidive", main="graphe de la fonction de survie")
#summary(surv.mydata1)
plot(surv.mydata1)
```

```{r}
plot(basehaz(cox), main=" fonction 
de  hasard de baseline", type="l")
```


```{r}
cox=coxph(Surv(origines, delta) ~ M + C + X1 + X2 + X3 + X4,data=mydata)
#Résumé du modèle de cox
summary(cox)
```

